### ISSUE TITLE
Error with parsing newest version of blockchain. Segwit, bech32.

### ISSUE THREAD

**Issue by swayll** [pldespaigne/blk_parser#1]
Error with parsing **blk01900.dat**. Segwit? bech32? You are planned to support it?

```
indexing BLOCKS . . .
end of indexing in 1.517676830291748 s
Block Index : [ 0 - 113 ]
indexing TX . . .
Traceback (most recent call last):
  File "blk_parser.py", line 124, in <module>
    tx_index = TxIndex(block_index) # create the tx index
  File "/Users/swayl/blk_parser/script/TxIndex.py", line 40, in __init__
    self.buildTxIndexFromBlockIndex(_block_index)
  File "/Users/swayl/blk_parser/script/TxIndex.py", line 111, in buildTxIndexFromBlockIndex
    if(byte_script_size[0] == 253): # varInt is on 2 bytes AFTER the prefix
IndexError: index out of range

```

**Comment by pldespaigne** [comment]
Hello :wave:
Thanks for raising this issue !
Unfortunately I do not maintain the repo anymore.
